### PR TITLE
added inv full logic..

### PR DESCRIPTION
**Pull request by Amitminer**

### CODE REVIEW

**Comment by GabBiswajit** [comment]
Can you add count on item remove?
Because my pc was death, add code which remove only 1 item from inventory don't remove all items, can you do or I do ?

**Comment by Amitminer** [comment]
> Can you add count on item remove? Because my pc was death, add code which remove only 1 item from inventory don't remove all items, can you do or I do ?

what do you mean by count on item?

**Comment by GabBiswajit** [comment]
Come in discord my id : ishan4990

**Comment by Amitminer** [comment]
> Can you add count on item remove? Because my pc was death, add code which remove only 1 item from inventory don't remove all items, can you do or I do ?

i dont understand.... you should doo.

**Pull request merged**
